deploy/HostedPCI/objects/HostedPCISettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>HostedPCI connection settings</description>
    <fields>
        <fullName>apiType__c</fullName>
        <defaultValue>&quot;pxyhpci&quot;</defaultValue>
        <label>Api Type</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>apiVersion__c</fullName>
        <defaultValue>&quot;1.0.1&quot;</defaultValue>
        <label>Api Version</label>
        <length>12</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>endPointAuth__c</fullName>
        <defaultValue>&apos;/iSynSApp/paymentAuth.action&apos;</defaultValue>
        <inlineHelpText>Assuming the full request param map is ready.Url string is made of the api url which is given by			HostedPCI + &quot;/iSynSApp/paymentAuth.action&quot;</inlineHelpText>
        <label>EndPoint  Auth</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>endPointBaseUrl__c</fullName>
        <defaultValue>&apos;https://api-sampqa1stg.c1.hostedpci.com&apos;</defaultValue>
        <inlineHelpText>Url string is made of the api url which is given by HostedPCI</inlineHelpText>
        <label>EndPoint BaseUrl</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>endPointCapture__c</fullName>
        <defaultValue>&apos;/iSynSApp/paymentCapture.action&apos;</defaultValue>
        <inlineHelpText>Assuming the full request param map is ready.Url string is made of the api url which is given by HostedPCI + &quot;/iSynSApp/paymentCapture.action&quot;</inlineHelpText>
        <label>EndPoint Capture</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>endPointCredit__c</fullName>
        <defaultValue>&apos;/iSynSApp/paymentCredit.action&apos;</defaultValue>
        <inlineHelpText>Assuming the full request param map is ready.Url string is made of the api url which is given by HostedPCI + &quot;/iSynSApp/paymentCredit.action&quot;</inlineHelpText>
        <label>EndPoint Credit</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>endPointSale__c</fullName>
        <defaultValue>&apos;/iSynSApp/paymentSale.action&apos;</defaultValue>
        <inlineHelpText>Assuming the full request param map is ready.Url string is made of the api url which is given by HostedPCI + &quot;/iSynSApp/paymentSale.action&quot;</inlineHelpText>
        <label>EndPoint Sale</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>endPointVoid__c</fullName>
        <defaultValue>&apos;/iSynSApp/paymentVoid.action&apos;</defaultValue>
        <inlineHelpText>Assuming the full request param map is ready.Url string is made of the api url which is given by HostedPCI + &quot;/iSynSApp/paymentVoid.action&quot;</inlineHelpText>
        <label>EndPoint Void</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>endPoint_manageCCMapPhoneAPI__c</fullName>
        <defaultValue>&apos;/iSynSApp/manageCCMapPhoneAPI.action&apos;</defaultValue>
        <inlineHelpText>Assuming the full request param map is ready.Url string is made of the api url which is given by HostedPCI + &quot;/iSynSApp/manageCCMapPhoneAPI.action&quot;</inlineHelpText>
        <label>EndPoint Phone API</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>userName__c</fullName>
        <inlineHelpText>The username is given by HostedPCI</inlineHelpText>
        <label>User Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>userPassKey__c</fullName>
        <description>The passkey is given by HostedPCI</description>
        <inlineHelpText>The passkey is given by HostedPCI</inlineHelpText>
        <label>User PassKey</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>HostedPCISettings</label>
</CustomObject>

deploy/HostedPCI/classes/HostedPciServiceUtil.cls
public class HostedPciServiceUtil{    
          
    public static String httpCalloutHostedPciAuthOnly(Map<String,String> hpciRequestParamMap){
        // Assuming the full request param map is ready
        // Url Endpoint is made of the api url which is given by
        // HostedPCI + "/iSynSApp/paymentAuth.action"                
        string endPoint = HostedPCISettings__c.getInstance().endPointAuth__c;
        string resultMsg = callUrl(endPoint, hpciRequestParamMap);
        
        return resultMsg; 
    }
    
    public static String httpCalloutHostedPciCaptureOnly(String processorRefId, Map<String,String> hpciRequestParamMap){
        // Assuming the full request param map is ready
        // Url Endpoint is made of the api url which is given by
        // HostedPCI + "/iSynSApp/paymentCapture.action"                                
        string endPoint = HostedPCISettings__c.getInstance().endPointCapture__c;
        hpciRequestParamMap.put('pxyTransaction.processorRefId', processorRefId);
        string resultMsg = callUrl(endPoint, hpciRequestParamMap);
        
        return resultMsg; 
    }
    
    public static String httpCalloutHostedPciCreditOnly(String processorRefId, Map<String,String> hpciRequestParamMap){
        // Assuming the full request param map is ready
        // Url Endpoint is made of the api url which is given by
        // HostedPCI + "/iSynSApp/paymentCredit.action"                
        string endPoint = HostedPCISettings__c.getInstance().endPointCredit__c;
        hpciRequestParamMap.put('pxyTransaction.processorRefId', processorRefId);
        string resultMsg = callUrl(endPoint, hpciRequestParamMap);
        
        return resultMsg; 
    }
    
    public static String httpCalloutHostedPciSaleOnly(Map<String,String> hpciRequestParamMap){        
        // Assuming the full request param map is ready
        // Url Endpoint is made of the api url which is given by
        // HostedPCI + "/iSynSApp/paymentSale.action"                
        string endPoint = HostedPCISettings__c.getInstance().endPointSale__c;
        string resultMsg = callUrl(endPoint, hpciRequestParamMap);
        
        return resultMsg; 
    }
    
    public static String httpCalloutHostedPciVoidOnly(String processorRefId, Map<String,String> hpciRequestParamMap){        
        // Assuming the full request param map is ready
        // Url Endpoint is made of the api url which is given by
        // HostedPCI + "/iSynSApp/paymentVoid.action"  
        string endPoint = HostedPCISettings__c.getInstance().endPointVoid__c;
        hpciRequestParamMap.put('pxyTransaction.processorRefId', processorRefId);
        string resultMsg = callUrl(endPoint, hpciRequestParamMap);
        
        return resultMsg;        
    }
    
    public static String httpCalloutHostedPciManageCCMApPhoneAPI(Map<String,String> hpciRequestParamMap){        
        // Assuming the full request param map is ready
        // Url Endpoint is made of the api url which is given by
        // HostedPCI + "/iSynSApp/manageCCMapPhoneAPI.action"  
        string endPoint = HostedPCISettings__c.getInstance().endPoint_manageCCMapPhoneAPI__c;
        string resultMsg = callUrl(endPoint, hpciRequestParamMap);
        
        return resultMsg;        
    }
    
    public static String callUrl(String urlEndPoint, Map<String, String> hpciRequestParamMap) {
        //Get connection settings from HostedPCISettings__c Custom Settings Class
        HostedPCISettings__c hostedPciSet = HostedPCISettings__c.getInstance();   
        
        // Populate hpciRequestParamMap with all the needed pairs of information
        hpciRequestParamMap.put('apiVersion', hostedPciSet.apiVersion__c);
        hpciRequestParamMap.put('apiType', hostedPciSet.apiType__c);
        // The username is given by HostedPCI
        hpciRequestParamMap.put('userName', hostedPciSet.userName__c);
        // The passkey is given by HostedPCI
        hpciRequestParamMap.put('userPassKey', hostedPciSet.userPassKey__c);     
        
        Http httpConn = new Http();
        HttpRequest httpReq = new HttpRequest();
        httpReq.setMethod('POST');      
        httpReq.setBody(encodeMsg(hpciRequestParamMap));
        httpReq.setEndpoint(hostedPciSet.endPointBaseUrl__c + urlEndPoint);
        HttpResponse httpRes = new HttpResponse();
        httpRes = httpConn.send(httpReq);
       
        return httpRes.getBody();
    }
    
    public static String encodeMsg(Map<String,String> hpciRequestParamMap){
        String encodedMsg = '';
        
        for (string msgKey : hpciRequestParamMap.keySet()){
            string msgValue = hpciRequestParamMap.get(msgKey);
            //fix null values
            if (string.isblank(msgValue)) msgValue='';
            encodedMsg += msgKey+'='+
            EncodingUtil.urlEncode(msgValue, 'UTF-8')+'&';
            //debug message value being added
            system.debug('TRACE: message bit '+msgKey+' added');
        }
        //add message termination
         encodedMsg += 'endofdata';
         
         return encodedMsg;
    }
    
    public static Map<String, String> parseQueryString(String queryStr) {
        Map<String, String> mapMsg = new Map<String, String>();
        if (queryStr == null)
          return mapMsg;
        List <String> params = queryStr.split('&'); 
        for (String param : params) {
          String name = '';
          String value = '';
          List<String> paramPair = param.split('=');
          if (paramPair != null && paramPair.size() > 0) {
            name = paramPair[0];
            if (paramPair.size() > 1 && paramPair[1] != null) {
              try {
                value = EncodingUtil.urlDecode(paramPair[1], 'UTF-8');
              } catch (StringException e) {
                system.debug('Could not decode:' + paramPair[1]);
              }
            }
          }
          mapMsg.put(name, value);
        } 
        return mapMsg; 
    } //END: parseQueryString
}