deploy/HostedPCI/objects/HostedPCIConfigurations__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>HostedPCI connection settings</description>
    <fields>
        <fullName>apiType__c</fullName>
        <defaultValue>&quot;pxyhpci&quot;</defaultValue>
        <label>Api Type</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>apiVersion__c</fullName>
        <defaultValue>&quot;1.0.1&quot;</defaultValue>
        <description>Api Version</description>
        <inlineHelpText>Api Version</inlineHelpText>
        <label>Api Version</label>
        <length>12</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>endPointAuth__c</fullName>
        <defaultValue>&quot;/iSynSApp/paymentAuth.action&quot;</defaultValue>
        <description>Assuming the full request param map is ready.Url string is made of the api url which is given by			HostedPCI + &quot;/iSynSApp/paymentAuth.action&quot;</description>
        <inlineHelpText>Assuming the full request param map is ready.Url string is made of the api url which is given by			HostedPCI + &quot;/iSynSApp/paymentAuth.action&quot;</inlineHelpText>
        <label>EndPoint  Auth</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>endPointBaseUrl__c</fullName>
        <defaultValue>&quot;https://apiservice.hostedpci.com&quot;</defaultValue>
        <description>Url string is made of the api url which is given by HostedPCI</description>
        <inlineHelpText>Url string is made of the api url which is given by HostedPCI</inlineHelpText>
        <label>EndPoint BaseUrl</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>endPointCapture__c</fullName>
        <defaultValue>&quot;/iSynSApp/paymentCapture.action&quot;</defaultValue>
        <description>Assuming the full request param map is ready.Url string is made of the api url which is given by HostedPCI + &quot;/iSynSApp/paymentCapture.action&quot;</description>
        <inlineHelpText>Assuming the full request param map is ready.Url string is made of the api url which is given by HostedPCI + &quot;/iSynSApp/paymentCapture.action&quot;</inlineHelpText>
        <label>EndPoint Capture</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>endPointSale__c</fullName>
        <defaultValue>&quot;/iSynSApp/paymentSale.action&quot;</defaultValue>
        <description>Assuming the full request param map is ready.Url string is made of the api url which is given by HostedPCI + &quot;/iSynSApp/paymentSale.action&quot;</description>
        <inlineHelpText>Assuming the full request param map is ready.Url string is made of the api url which is given by HostedPCI + &quot;/iSynSApp/paymentSale.action&quot;</inlineHelpText>
        <label>EndPoint Sale</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>endPointVoid__c</fullName>
        <defaultValue>&quot;/iSynSApp/paymentVoid.action&quot;</defaultValue>
        <description>Assuming the full request param map is ready.Url string is made of the api url which is given by HostedPCI + &quot;/iSynSApp/paymentVoid.action&quot;</description>
        <inlineHelpText>Assuming the full request param map is ready.Url string is made of the api url which is given by HostedPCI + &quot;/iSynSApp/paymentVoid.action&quot;</inlineHelpText>
        <label>EndPoint Void</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>locationName__c</fullName>
        <defaultValue>&quot;salesforce1&quot;</defaultValue>
        <description>The Location(iframe) Name is given by HostedPCI</description>
        <inlineHelpText>The Location(iframe) Name is given by HostedPCI</inlineHelpText>
        <label>Location Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>siteId__c</fullName>
        <defaultValue>&quot;528160&quot;</defaultValue>
        <description>The Site Id is given by HostedPCI</description>
        <inlineHelpText>The Site Id is given by HostedPCI</inlineHelpText>
        <label>Site Id</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>userName__c</fullName>
        <defaultValue>&quot;sampqa1stgAdmAPI&quot;</defaultValue>
        <description>The username is given by HostedPCI</description>
        <inlineHelpText>The username is given by HostedPCI</inlineHelpText>
        <label>User Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>userPassKey__c</fullName>
        <defaultValue>&quot;.OQdIHVtVJSg-W-Zr40QQGY1xyhvGjUH&quot;</defaultValue>
        <description>The passkey is given by HostedPCI</description>
        <inlineHelpText>The passkey is given by HostedPCI</inlineHelpText>
        <label>User PassKey</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>HostedPCISettings</label>
</CustomObject>

deploy/HostedPCI/classes/PaymentTerminalController_Test.cls
@isTest
public class PaymentTerminalController_Test {
    static PageReference pageRef;
    static PaymentTerminalController controller;
    static HostedPCIConfigurations__c testConf;
    
    @isTest 
    private static void init(){
        pageRef = Page.PaymentTerminal;
        
        pageRef.getParameters().put('authTxnId', 'YmRnU3l3M0IyeTJsaHhPb1UwVTA');
        pageRef.getParameters().put('ccNum', '4111000570001111');
        pageRef.getParameters().put('ccCVV', '200');
        pageRef.getParameters().put('cardType', 'Visa');           
        pageRef.getParameters().put('expiryMonth', '01');           
        pageRef.getParameters().put('expiryYear', '2016');           
        pageRef.getParameters().put('firstName', 'Test');           
        pageRef.getParameters().put('lastName', 'Test');           
        pageRef.getParameters().put('address1', 'Place');           
        pageRef.getParameters().put('address2', '');           
        pageRef.getParameters().put('city', 'Toronto');           
        pageRef.getParameters().put('state', 'On');           
		pageRef.getParameters().put('zip', 'l5k 7o2');           
        pageRef.getParameters().put('country', 'Canada');           
        pageRef.getParameters().put('currency', 'CAD');           
        pageRef.getParameters().put('amount', '10');           
        pageRef.getParameters().put('comment', 'sale');           
        pageRef.getParameters().put('paymentProfile', 'DEF');
        
        Test.setCurrentPage(pageRef);
        //set our mock class for callouts
		Test.setMock(HttpCalloutMock.class, new	mock_HostedPciServiceUtil());
        controller = new PaymentTerminalController();
    }
    
    public static testMethod void PaymentTerminalController_PopulateData_Test() {
        init();
		
		//start the test and separate DML flow
		test.StartTest();
        	controller.populateData();
        	System.assertNotEquals('', controller.SiteId);
        	System.assertNotEquals('', controller.LocationName);
        	System.assertNotEquals('', controller.fullParentQStr);
        	System.assertNotEquals('', controller.fullParentHost);
        //stoptest
		test.StopTest();        
    }
    
    public static testMethod void PaymentTerminalController_PopulateData2_Test() {
        init();
		
		//start the test and separate DML flow
		test.StartTest();
        	testConf = new HostedPCIConfigurations__c();
            testConf.userName__c = 'test user';
            testConf.apiType__c ='pxyhpci';
            testConf.apiVersion__c ='1.0.1';
            testConf.endPointAuth__c='/iSynSApp/paymentAuth.action';
            testConf.endPointBaseUrl__c='https://apiservice.hostedpci.com/iSynSApp/paymentAuth.action/';
            testConf.endPointCapture__c='/iSynSApp/paymentCapture.action';
            testConf.endPointCapture__c='/iSynSApp/paymentCapture.action';
            testConf.endPointSale__c='/iSynSApp/paymentSale.action';
            testConf.endPointVoid__c='/iSynSApp/paymentVoid.action';
            testConf.locationName__c='salesforce1';
            testConf.siteId__c='528160';
            testConf.userPassKey__c='Test password';
            insert testConf;
        	controller.populateData();
        	System.assertNotEquals('', controller.SiteId);
        	System.assertNotEquals('', controller.LocationName);
        	System.assertNotEquals('', controller.fullParentQStr);
        	System.assertNotEquals('', controller.fullParentHost);
        //stoptest
		test.StopTest();        
    }
    
    public static testMethod void PaymentTerminalController_PopulateData_negative_Test() {
        init();
		
		//start the test and separate DML flow
		test.StartTest();
        	String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com';
        	// This code runs as the system user
        	Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
        	User newUser = new User(Alias = 'standt', Email='standarduser@testorg.com',
       	 		EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
        		LocaleSidKey='en_US', ProfileId = p.Id,
        		TimeZoneSidKey='America/Los_Angeles', UserName=uniqueUserName);
        	
        	System.runAs(newUser) {
        		controller.populateData();
        		System.assert(ApexPages.hasMessages(ApexPages.severity.FATAL));
            }
        //stoptest
		test.StopTest();        
    }
    
    public static testMethod void PaymentTerminalController_ProcessPayment_Test(){
        Map<String,String> hostedPciMsgMap;
        String fullMsg;
        
        init();
        
        //start the test 
		test.StartTest();
        	hostedPciMsgMap = PaymentTerminalController.processPayment('4111000570001111', '200', 'Visa', '01',
                    '2016', 'Test','Test', 'Place', '', 'Toronto', 'On', 'l5k 7o2', 'Canada',
                	'CAD', '10', 'sale', 'DEF','');
        	fullMsg = hostedPciMsgMap.get('fullMsg');
        	System.assertNotEquals(null, fullMsg);
        //stoptest
		test.StopTest();
    }
    
    public static testMethod void PaymentTerminalController_ProcessPayment_VerifyEnrollTest(){
        Map<String,String> hostedPciMsgMap;
        String fullMsg;
        
        init();
        
        //start the test 
		test.StartTest();
        	hostedPciMsgMap = PaymentTerminalController.processPayment('4111000570001111', '200', 'Visa', '01',
                    '2016', 'Test','Test', 'Place', '', 'Toronto', 'On', 'l5k 7o2', 'Canada',
                	'CAD', '10', 'sale', 'DEF','verifyenroll');
        	fullMsg = hostedPciMsgMap.get('fullMsg');
        	System.assertNotEquals(null, fullMsg);
        //stoptest
		test.StopTest();
    }
    
    public static testMethod void PaymentTerminalController_ProcessThreeDSecPayment_Test(){
        String pageName;        
        
        init();
        
        //start the test 
		test.StartTest();        	
        	PageReference nextPage = controller.processThreeDSecPayment();
        	pageName = nextPage.getUrl();        	
        	System.assertEquals(true, pageName.containsIgnoreCase('ThreeDSecPinFrame'));
        //stoptest
		test.StopTest();
    }
}