deploy/HostedPCI/objects/HostedPCISettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>HostedPCI connection settings</description>
    <fields>
        <fullName>endPointBaseUrl__c</fullName>
        <defaultValue>&apos;https://api-sampqa1stg.c1.hostedpci.com&apos;</defaultValue>
        <inlineHelpText>Url string is made of the api url which is given by HostedPCI</inlineHelpText>
        <label>EndPoint BaseUrl</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>locationName__c</fullName>
        <defaultValue>&quot;javasample1&quot;</defaultValue>
        <inlineHelpText>The Location(iframe) Name is given by HostedPCI</inlineHelpText>
        <label>Location Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>siteId__c</fullName>
        <defaultValue>&quot;528160&quot;</defaultValue>
        <inlineHelpText>The Site Id is given by HostedPCI</inlineHelpText>
        <label>Site Id</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>userName__c</fullName>
        <inlineHelpText>The username is given by HostedPCI</inlineHelpText>
        <label>User Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>userPassKey__c</fullName>
        <description>The passkey is given by HostedPCI</description>
        <inlineHelpText>The passkey is given by HostedPCI</inlineHelpText>
        <label>User PassKey</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>HostedPCISettings</label>
</CustomObject>

deploy/HostedPCI/classes/HostedPCISettingsController.cls
public class HostedPCISettingsController {
    public String userName;
    public String userPassKey;
    public String endPointBaseUrl;
    public String siteId;
    public String locationName;
    public boolean displayPopup {get; set;} 
    public String modalTitle ;
    public String buttonId {get;set;}
    public String newValue{get;set;}
    HostedPCISettings__c hostedPciSet;
    
    public HostedPCISettingsController(){
        hostedPciSet = HostedPCISettings__c.getInstance();                        
        userName = hostedPciSet.userName__c;
        userPassKey = hostedPciSet.userPassKey__c;
        endPointBaseUrl = hostedPciSet.endPointBaseUrl__c;
        siteId = hostedPciSet.siteId__c;
        locationName = hostedPciSet.locationName__c;
    }
    
    public string getUserName(){
        return userName;        
    }
    private void setUserName(){
        if(newValue.length()>0 &&(userName!=newValue)){
            try{
                HostedPCISettings__c hostedPciConf = HostedPCISettings__c.getOrgDefaults();
                hostedPciConf.userName__c = newValue;
                update hostedPciConf;
                userName = newValue;
            }catch (DmlException e) {
            	System.debug(e.getMessage());
            	ApexPages.addMessages(e);
        	} 
        }
            
    }
        
    public string getUserPassKey(){        
        return userPassKey;
    }
    private void setUserPassKey(){
        if(newValue.length()>0 &&(userName!=newValue)){
            try{
                HostedPCISettings__c hostedPciConf = HostedPCISettings__c.getOrgDefaults();
                hostedPciConf.userPassKey__c = newValue;
                update hostedPciConf;
                userPassKey = newValue;
            }catch (DmlException e) {
            	System.debug(e.getMessage());
            	ApexPages.addMessages(e);
        	} 
        }        
    }  
    
    public string getEndPointBaseUrl(){
        return endPointBaseUrl;
    }
    private void setEndPointBaseUrl(){ 
        if(newValue.length()>0 &&(userName!=newValue)){
            try{
                HostedPCISettings__c hostedPciConf = HostedPCISettings__c.getOrgDefaults();
                hostedPciConf.endPointBaseUrl__c = newValue;
                update hostedPciConf;
                endPointBaseUrl = newValue;
            }catch (DmlException e) {
            	System.debug(e.getMessage());
            	ApexPages.addMessages(e);
        	} 
        }
    }   
    
    public string getSiteId(){
        return siteId;
    }
    private void setSiteId(){
       if(newValue.length()>0 &&(userName!=newValue)){
            try{
                HostedPCISettings__c hostedPciConf = HostedPCISettings__c.getOrgDefaults();
                hostedPciConf.siteId__c = newValue;
                update hostedPciConf;
                siteId = newValue;
            }catch (DmlException e) {
            	System.debug(e.getMessage());
            	ApexPages.addMessages(e);
        	} 
        } 
    }
    
    public string getLocationName(){
        return locationName;
    }
    private void setLocationName(){
        if(newValue.length()>0 &&(userName!=newValue)){
            try{
                HostedPCISettings__c hostedPciConf = HostedPCISettings__c.getOrgDefaults();
                hostedPciConf.locationName__c = newValue;
                update hostedPciConf;
                locationName = newValue;
            }catch (DmlException e) {
            	System.debug(e.getMessage());
            	ApexPages.addMessages(e);
        	} 
        }
    }   
    
    public void setModalTitle(String newModalTitle){
        modalTitle = newModalTitle;
    }
    public String getModalTitle(){
        return 'Edit mode: ' + modalTitle ;
    }
     
    public PageReference save(){
        if(buttonId=='userName')
            setUserName();
        if(buttonId=='userPassKey')
            setUserPassKey();
        if(buttonId=='endPointBaseUrl')
            setEndPointBaseUrl();
        if(buttonId=='siteId')
            setSiteId();
        if(buttonId=='locationName')
            setLocationName();
        displayPopup = false;
        newValue='';
        return null;
    }
    public void closePopup() { 
        newValue='';
		displayPopup = false;   
    }    
    public void showPopup() { 
        setModalTitle(buttonId);
        displayPopup = true;   
    }    
}